#!/usr/bin/env bash
#
# taskboard.sh - Generate TASKBOARD.md from task files
#
# Works with both .doyaken/ (new) and .claude/ (legacy) structures.
#
set -euo pipefail

# Configuration
DOYAKEN_HOME="${DOYAKEN_HOME:-$HOME/.doyaken}"
DOYAKEN_PROJECT="${DOYAKEN_PROJECT:-$(pwd)}"

# Detect project structure
if [ -d "$DOYAKEN_PROJECT/.doyaken/tasks" ]; then
  TASKS_DIR="$DOYAKEN_PROJECT/.doyaken/tasks"
  TASK_PATH_PREFIX=".doyaken/tasks"
elif [ -d "$DOYAKEN_PROJECT/.claude/tasks" ]; then
  TASKS_DIR="$DOYAKEN_PROJECT/.claude/tasks"
  TASK_PATH_PREFIX=".claude/tasks"
else
  echo "Error: No task directory found in $DOYAKEN_PROJECT"
  exit 1
fi

OUTPUT_FILE="$DOYAKEN_PROJECT/TASKBOARD.md"

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
  echo -e "${BLUE}[taskboard]${NC} $1"
}

log_success() {
  echo -e "${GREEN}[taskboard]${NC} $1"
}

# Count tasks in each state
count_todo=$(find "$TASKS_DIR/todo" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_doing=$(find "$TASKS_DIR/doing" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_done=$(find "$TASKS_DIR/done" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

log_info "Generating TASKBOARD.md..."
log_info "Found: $count_todo todo, $count_doing doing, $count_done done"

# Start generating the taskboard
cat > "$OUTPUT_FILE" << 'HEADER'
# Taskboard

> Auto-generated by `doyaken tasks` or `lib/taskboard.sh`
> Last updated: TIMESTAMP

## Summary

| Status | Count |
|--------|-------|
HEADER

# Replace timestamp
timestamp=$(date '+%Y-%m-%d %H:%M:%S')
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/TIMESTAMP/$timestamp/" "$OUTPUT_FILE"
else
  sed -i "s/TIMESTAMP/$timestamp/" "$OUTPUT_FILE"
fi

# Add counts
echo "| Doing | $count_doing |" >> "$OUTPUT_FILE"
echo "| Todo | $count_todo |" >> "$OUTPUT_FILE"
echo "| Done | $count_done |" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to extract task title from file
get_task_title() {
  local file="$1"
  head -5 "$file" | grep -m1 "^# Task:" | sed 's/^# Task: //' || basename "$file" .md
}

# Function to extract priority from filename
get_priority_label() {
  local filename="$1"
  case "${filename:0:3}" in
    001) echo "Critical" ;;
    002) echo "High" ;;
    003) echo "Medium" ;;
    004) echo "Low" ;;
    *) echo "Unknown" ;;
  esac
}

# Function to get assigned agent from task file
get_assigned_agent() {
  local file="$1"
  grep "| Assigned To |" "$file" 2>/dev/null | sed 's/.*| Assigned To | *//' | sed 's/ *|.*//' | tr -d '`' || echo ""
}

# In Progress section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## In Progress" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_doing" -eq 0 ]; then
  echo "_No tasks in progress_" >> "$OUTPUT_FILE"
else
  for file in "$TASKS_DIR/doing"/*.md; do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    priority=$(get_priority_label "$filename")
    agent=$(get_assigned_agent "$file")
    agent_info=""
    [ -n "$agent" ] && agent_info=" (${agent})"
    echo "- **[$filename]($TASK_PATH_PREFIX/doing/$filename)** - $title [$priority]$agent_info" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# Todo section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Todo" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_todo" -eq 0 ]; then
  echo "_No pending tasks_" >> "$OUTPUT_FILE"
else
  # Sort by filename (which gives priority order)
  for file in $(find "$TASKS_DIR/todo" -maxdepth 1 -name "*.md" 2>/dev/null | sort); do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    priority=$(get_priority_label "$filename")
    echo "- **[$filename]($TASK_PATH_PREFIX/todo/$filename)** - $title [$priority]" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# Done section (last 10)
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Recently Completed (Last 10)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_done" -eq 0 ]; then
  echo "_No completed tasks_" >> "$OUTPUT_FILE"
else
  # Sort by modification time, most recent first, limit to 10
  for file in $(find "$TASKS_DIR/done" -maxdepth 1 -name "*.md" -exec ls -t {} + 2>/dev/null | head -10); do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    echo "- **[$filename]($TASK_PATH_PREFIX/done/$filename)** - $title" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# Footer
cat >> "$OUTPUT_FILE" << 'FOOTER'
---

## Quick Commands

```bash
# Regenerate this file
doyaken tasks

# Run agent for 1 task
doyaken run 1

# Run agent for 5 tasks (default)
doyaken

# Create a new task
doyaken tasks new "My task title"

# Check project status
doyaken status

# Health check
doyaken doctor
```
FOOTER

log_success "Generated $OUTPUT_FILE"
