#!/usr/bin/env bash
#
# taskboard.sh - Generate TASKBOARD.md from task files
#
# Works with both .doyaken/ (new) and .claude/ (legacy) structures.
#
set -euo pipefail

# Configuration
DOYAKEN_HOME="${DOYAKEN_HOME:-$HOME/.doyaken}"
DOYAKEN_PROJECT="${DOYAKEN_PROJECT:-$(pwd)}"

# Source centralized logging
_TASKBOARD_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$_TASKBOARD_SCRIPT_DIR/logging.sh" ]]; then
  source "$_TASKBOARD_SCRIPT_DIR/logging.sh"
  set_log_prefix "taskboard"
else
  # Fallback colors
  BLUE='\033[0;34m'
  GREEN='\033[0;32m'
  NC='\033[0m'
  log_info() { echo -e "${BLUE}[taskboard]${NC} $1"; }
  log_success() { echo -e "${GREEN}[taskboard]${NC} $1"; }
fi

# Detect project structure
if [ -d "$DOYAKEN_PROJECT/.doyaken/tasks" ]; then
  TASKS_DIR="$DOYAKEN_PROJECT/.doyaken/tasks"
  TASK_PATH_PREFIX=".doyaken/tasks"
elif [ -d "$DOYAKEN_PROJECT/.claude/tasks" ]; then
  TASKS_DIR="$DOYAKEN_PROJECT/.claude/tasks"
  TASK_PATH_PREFIX=".claude/tasks"
else
  echo "Error: No task directory found in $DOYAKEN_PROJECT"
  exit 1
fi

OUTPUT_FILE="$DOYAKEN_PROJECT/TASKBOARD.md"

# Get the actual folder path, supporting both old and new naming
get_task_folder() {
  local state="$1"
  case "$state" in
    blocked) [ -d "$TASKS_DIR/1.blocked" ] && echo "$TASKS_DIR/1.blocked" && return ;;
    todo)    [ -d "$TASKS_DIR/2.todo" ] && echo "$TASKS_DIR/2.todo" && return ;;
    doing)   [ -d "$TASKS_DIR/3.doing" ] && echo "$TASKS_DIR/3.doing" && return ;;
    done)    [ -d "$TASKS_DIR/4.done" ] && echo "$TASKS_DIR/4.done" && return ;;
  esac
  echo "$TASKS_DIR/$state"
}

# Get folder paths
BLOCKED_DIR=$(get_task_folder "blocked")
TODO_DIR=$(get_task_folder "todo")
DOING_DIR=$(get_task_folder "doing")
DONE_DIR=$(get_task_folder "done")

# Count tasks in each state
count_blocked=$(find "$BLOCKED_DIR" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_todo=$(find "$TODO_DIR" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_doing=$(find "$DOING_DIR" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_done=$(find "$DONE_DIR" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

log_info "Generating TASKBOARD.md..."
log_info "Found: $count_blocked blocked, $count_todo todo, $count_doing doing, $count_done done"

# Start generating the taskboard
cat > "$OUTPUT_FILE" << 'HEADER'
# Taskboard

> Auto-generated by `doyaken tasks` or `lib/taskboard.sh`
> Last updated: TIMESTAMP

## Summary

| Status | Count |
|--------|-------|
HEADER

# Replace timestamp
timestamp=$(date '+%Y-%m-%d %H:%M:%S')
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/TIMESTAMP/$timestamp/" "$OUTPUT_FILE"
else
  sed -i "s/TIMESTAMP/$timestamp/" "$OUTPUT_FILE"
fi

# Add counts
echo "| Blocked | $count_blocked |" >> "$OUTPUT_FILE"
echo "| Todo | $count_todo |" >> "$OUTPUT_FILE"
echo "| Doing | $count_doing |" >> "$OUTPUT_FILE"
echo "| Done | $count_done |" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to extract task title from file
get_task_title() {
  local file="$1"
  head -5 "$file" | grep -m1 "^# Task:" | sed 's/^# Task: //' || basename "$file" .md
}

# Function to extract priority from filename
get_priority_label() {
  local filename="$1"
  case "${filename:0:3}" in
    001) echo "Critical" ;;
    002) echo "High" ;;
    003) echo "Medium" ;;
    004) echo "Low" ;;
    *) echo "Unknown" ;;
  esac
}

# Function to get assigned agent from task file
get_assigned_agent() {
  local file="$1"
  grep "| Assigned To |" "$file" 2>/dev/null | sed 's/.*| Assigned To | *//' | sed 's/ *|.*//' | tr -d '`' || echo ""
}

# Get folder basename for links
get_folder_name() {
  local dir="$1"
  basename "$dir"
}

# Blocked section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Blocked" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_blocked" -eq 0 ]; then
  echo "_No blocked tasks_" >> "$OUTPUT_FILE"
else
  blocked_folder=$(get_folder_name "$BLOCKED_DIR")
  for file in $(find "$BLOCKED_DIR" -maxdepth 1 -name "*.md" 2>/dev/null | sort); do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    priority=$(get_priority_label "$filename")
    echo "- **[$filename]($TASK_PATH_PREFIX/$blocked_folder/$filename)** - $title [$priority]" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# In Progress section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## In Progress" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_doing" -eq 0 ]; then
  echo "_No tasks in progress_" >> "$OUTPUT_FILE"
else
  doing_folder=$(get_folder_name "$DOING_DIR")
  for file in "$DOING_DIR"/*.md; do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    priority=$(get_priority_label "$filename")
    agent=$(get_assigned_agent "$file")
    agent_info=""
    [ -n "$agent" ] && agent_info=" (${agent})"
    echo "- **[$filename]($TASK_PATH_PREFIX/$doing_folder/$filename)** - $title [$priority]$agent_info" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# Todo section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Todo" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_todo" -eq 0 ]; then
  echo "_No pending tasks_" >> "$OUTPUT_FILE"
else
  todo_folder=$(get_folder_name "$TODO_DIR")
  # Sort by filename (which gives priority order)
  for file in $(find "$TODO_DIR" -maxdepth 1 -name "*.md" 2>/dev/null | sort); do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    priority=$(get_priority_label "$filename")
    echo "- **[$filename]($TASK_PATH_PREFIX/$todo_folder/$filename)** - $title [$priority]" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# Done section (last 10)
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Recently Completed (Last 10)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_done" -eq 0 ]; then
  echo "_No completed tasks_" >> "$OUTPUT_FILE"
else
  done_folder=$(get_folder_name "$DONE_DIR")
  # Sort by modification time, most recent first, limit to 10
  for file in $(find "$DONE_DIR" -maxdepth 1 -name "*.md" -exec ls -t {} + 2>/dev/null | head -10); do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    title=$(get_task_title "$file")
    echo "- **[$filename]($TASK_PATH_PREFIX/$done_folder/$filename)** - $title" >> "$OUTPUT_FILE"
  done
fi
echo "" >> "$OUTPUT_FILE"

# Footer
cat >> "$OUTPUT_FILE" << 'FOOTER'
---

## Quick Commands

```bash
# Regenerate this file
doyaken tasks

# Run agent for 1 task
doyaken run 1

# Run agent for 5 tasks (default)
doyaken

# Create a new task
doyaken tasks new "My task title"

# Check project status
doyaken status

# Health check
doyaken doctor
```
FOOTER

log_success "Generated $OUTPUT_FILE"
