#!/usr/bin/env bats
#
# Unit tests for lib/taskboard.sh
#

load "../test_helper"

setup() {
  export TEST_TEMP_DIR
  TEST_TEMP_DIR="$(mktemp -d)"

  # Set up test environment
  export DOYAKEN_HOME="$TEST_TEMP_DIR/home"
  export DOYAKEN_PROJECT="$TEST_TEMP_DIR/project"

  # Create directory structure
  mkdir -p "$DOYAKEN_PROJECT/.doyaken/tasks/1.blocked"
  mkdir -p "$DOYAKEN_PROJECT/.doyaken/tasks/2.todo"
  mkdir -p "$DOYAKEN_PROJECT/.doyaken/tasks/3.doing"
  mkdir -p "$DOYAKEN_PROJECT/.doyaken/tasks/4.done"
  mkdir -p "$DOYAKEN_HOME"

  # Source dependencies
  source "$PROJECT_ROOT/lib/logging.sh"
  source "$PROJECT_ROOT/lib/project.sh"
}

teardown() {
  if [[ -d "${TEST_TEMP_DIR:-}" ]]; then
    rm -rf "$TEST_TEMP_DIR"
  fi
}

# Helper to create a test task
create_test_task() {
  local id="$1"
  local state="$2"
  local title="${3:-Test Task}"

  local dir
  case "$state" in
    blocked) dir="$DOYAKEN_PROJECT/.doyaken/tasks/1.blocked" ;;
    todo) dir="$DOYAKEN_PROJECT/.doyaken/tasks/2.todo" ;;
    doing) dir="$DOYAKEN_PROJECT/.doyaken/tasks/3.doing" ;;
    done) dir="$DOYAKEN_PROJECT/.doyaken/tasks/4.done" ;;
  esac

  cat > "$dir/$id.md" << EOF
# Task: $title

| Field | Value |
|-------|-------|
| Priority | Medium |
| Status | $state |
EOF
}

# ============================================================================
# Basic Functionality Tests
# ============================================================================

@test "taskboard.sh: detects .doyaken project structure" {
  source "$PROJECT_ROOT/lib/taskboard.sh"

  [ "$TASKS_DIR" = "$DOYAKEN_PROJECT/.doyaken/tasks" ]
  [ "$TASK_PATH_PREFIX" = ".doyaken/tasks" ]
}

@test "taskboard.sh: detects legacy .claude structure" {
  # Remove .doyaken and create .claude structure
  rm -rf "$DOYAKEN_PROJECT/.doyaken"
  mkdir -p "$DOYAKEN_PROJECT/.claude/tasks/1.blocked"
  mkdir -p "$DOYAKEN_PROJECT/.claude/tasks/2.todo"
  mkdir -p "$DOYAKEN_PROJECT/.claude/tasks/3.doing"
  mkdir -p "$DOYAKEN_PROJECT/.claude/tasks/4.done"

  source "$PROJECT_ROOT/lib/taskboard.sh"

  [ "$TASKS_DIR" = "$DOYAKEN_PROJECT/.claude/tasks" ]
  [ "$TASK_PATH_PREFIX" = ".claude/tasks" ]
}

@test "taskboard.sh: exits when no task directory found" {
  rm -rf "$DOYAKEN_PROJECT/.doyaken"
  rm -rf "$DOYAKEN_PROJECT/.claude"

  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 1 ]
  [[ "$output" == *"No task directory found"* ]]
}

@test "get_task_folder: returns correct paths" {
  source "$PROJECT_ROOT/lib/taskboard.sh"

  run get_task_folder "blocked"
  [ "$output" = "$DOYAKEN_PROJECT/.doyaken/tasks/1.blocked" ]

  run get_task_folder "todo"
  [ "$output" = "$DOYAKEN_PROJECT/.doyaken/tasks/2.todo" ]

  run get_task_folder "doing"
  [ "$output" = "$DOYAKEN_PROJECT/.doyaken/tasks/3.doing" ]

  run get_task_folder "done"
  [ "$output" = "$DOYAKEN_PROJECT/.doyaken/tasks/4.done" ]
}

@test "taskboard.sh: generates TASKBOARD.md file" {
  # Create some test tasks
  create_test_task "001-001-task1" "blocked"
  create_test_task "002-001-task2" "todo"
  create_test_task "002-002-task3" "todo"
  create_test_task "003-001-task4" "doing"

  # Run taskboard generation
  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 0 ]

  # Check output file exists
  [ -f "$DOYAKEN_PROJECT/TASKBOARD.md" ]

  # Verify content
  local content
  content=$(cat "$DOYAKEN_PROJECT/TASKBOARD.md")

  # Check header
  [[ "$content" == *"# Taskboard"* ]]
  [[ "$content" == *"Auto-generated by"* ]]

  # Check counts in summary table
  [[ "$content" == *"| Blocked | 1 |"* ]]
  [[ "$content" == *"| Todo | 2 |"* ]]
  [[ "$content" == *"| Doing | 1 |"* ]]
  [[ "$content" == *"| Done | 0 |"* ]]
}

@test "taskboard.sh: handles empty task folders" {
  # Run without any tasks
  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 0 ]

  local content
  content=$(cat "$DOYAKEN_PROJECT/TASKBOARD.md")

  # All counts should be 0
  [[ "$content" == *"| Blocked | 0 |"* ]]
  [[ "$content" == *"| Todo | 0 |"* ]]
  [[ "$content" == *"| Doing | 0 |"* ]]
  [[ "$content" == *"| Done | 0 |"* ]]
}

@test "taskboard.sh: includes timestamp" {
  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 0 ]

  local content
  content=$(cat "$DOYAKEN_PROJECT/TASKBOARD.md")

  # Check for date pattern (YYYY-MM-DD HH:MM:SS)
  [[ "$content" =~ [0-9]{4}-[0-9]{2}-[0-9]{2}\ [0-9]{2}:[0-9]{2}:[0-9]{2} ]]
}

# ============================================================================
# Edge Cases
# ============================================================================

@test "taskboard.sh: handles tasks with special characters in names" {
  create_test_task "001-001-task-with-dash" "todo"
  create_test_task "001-002-task.with.dots" "todo"
  create_test_task "001-003-task_with_underscores" "todo"

  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 0 ]

  local content
  content=$(cat "$DOYAKEN_PROJECT/TASKBOARD.md")
  [[ "$content" == *"| Todo | 3 |"* ]]
}

@test "taskboard.sh: handles missing task state folders" {
  # Remove some folders
  rmdir "$DOYAKEN_PROJECT/.doyaken/tasks/1.blocked"
  rmdir "$DOYAKEN_PROJECT/.doyaken/tasks/4.done"

  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 0 ]

  # Should still generate taskboard
  [ -f "$DOYAKEN_PROJECT/TASKBOARD.md" ]
}

@test "taskboard.sh: overwrites existing TASKBOARD.md" {
  # Create existing file with different content
  echo "Old content" > "$DOYAKEN_PROJECT/TASKBOARD.md"

  create_test_task "001-001-new-task" "todo"

  run bash -c "cd '$DOYAKEN_PROJECT' && source '$PROJECT_ROOT/lib/taskboard.sh'"
  [ "$status" -eq 0 ]

  local content
  content=$(cat "$DOYAKEN_PROJECT/TASKBOARD.md")

  # Old content should be replaced
  [[ "$content" != *"Old content"* ]]
  [[ "$content" == *"# Taskboard"* ]]
}